// Generated by CoffeeScript 1.9.2
(function() {
  var pongular;

  process.env.NODE_ENV = process.env.NODE_ENV || 'development';

  pongular = require('pongular').pongular;

  require('../index.js');

  pongular.injector(['pong-express']).invoke(function(serve, controller) {
    var complexController, expressConfig, httpConfig, simpleController;
    simpleController = controller('/', function(req, res) {
      return res.json([1, 2, 3]);
    });
    complexController = controller(function(router) {
      router.route('/').get(function(req, res) {
        return res.json([4, 5, 6]);
      });
      return router.route('/list').get(function(req, res) {
        return res.json([7, 8, 9]);
      });
    });
    httpConfig = require('./config/environment');
    expressConfig = require('./config/express');
    return serve(httpConfig.port, function(app) {
      expressConfig(app);
      app.use('/foo', simpleController);
      app.use('/bar', complexController);
      return app.route('/*').get(function(req, res) {
        return res.sendFile('./test/index.html');
      });
    });
  });

}).call(this);
