// Generated by CoffeeScript 1.9.2
(function() {
  var pongular;

  pongular = require('pongular').pongular;

  module.exports = pongular.module('pong-express', []).service('express', function() {
    return require('express');
  }).service('http', require('http')).service('expressApp', function(express) {
    return express();
  });

}).call(this);
