// Generated by CoffeeScript 1.9.2
(function() {
  var pongular;

  pongular = require('pongular').pongular;

  module.exports = pongular.module('pong-express', []).service('express', function() {
    return function(port, init) {
      var app, server;
      app = require('express')();
      init(app);
      return server = app.listen(port, function() {
        var address;
        address = server.address();
        return console.log('Express server listening at %s:%s', address.address, address.port);
      });
    };
  });

}).call(this);
