// Generated by CoffeeScript 1.9.2
(function() {
  var pongular;

  pongular = require('pongular').pongular;

  require('./index.js');

  pongular.module('test', ['pong-express']).service('myApp', function(express) {
    return express();
  });

  pongular.injector(['test']).invoke(function(myApp) {
    return console.log(myApp);
  });

  pongular.injector(['pong-express']).invoke(function(express) {
    return console.log('yes');
  });

}).call(this);
